### ISSUE TITLE
Allow for https protocoll

### ISSUE THREAD

**Issue by felixmw** [johnholbrook/streamdeck-pihole#9]
My pihole is running behind a reverse proxy and ssl encryption is applied. Since the 'http' protocol ist hard coded in your scripts I am not able to use your stream deck plugin. It would be great if one could define the protocol either as part of the address or as a separate variable.

Thanks a lot,
best,
Felix

**Comment by AquaRelliux** [comment]
Your steamdeck is on the same network as your pihole? You should use split-dns to avoid NAT problems also you should go directly to your pihole via http on your internal network. This will be better security wise and performance wise

**Comment by digas** [comment]
What do you have to do with and how our network is configured ? This is not the question or the request of the issue . 
The question / request of the issue is can you change it to be able to use https request or not ? simple .
Imagine i have different networks all in the my same network , imagine i'm using pihole on a docker and i actually use VM's this is not the point and i believe it's no own will come here to put question about a pihole not working ..
The question is can you change from hardcoding allow the client to choose which protocol he wants to make the request over http or https ?  thank you

**Comment by johnholbrook** [comment]
This feature was added in version 1.2.0, which is now available from the [releases page](https://github.com/johnholbrook/streamdeck-pihole/releases/tag/v1.2.0) or from the [stream deck store](https://apps.elgato.com/plugins/us.johnholbrook.pihole).
